title: Cornel's Blog
description: Some personal thoughts from another citizen of the internet named Cornelius Yan Mintareja
theme: jekyll-theme-cayman

defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: :slug:output_ext

  -
    scope:
      type: "pages"
    values:
      permalink: :basename:output_ext